### ISSUE TITLE
ERROR: tcpserver 41826 : error writing message: Broken pipe

### ISSUE THREAD

**Issue by Panshark** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#36]
Hi @praveen-palanisamy ,

Will this error be the problem?

```
ERROR: tcpserver 37004 : error reading message: End of file 
ERROR: tcpserver 37003 : error writing message: Broken pipe
```

I set `"discrete_actions": False` to find out how well can the model worked in the continuous action area, and received this error.

**Comment by praveen-palanisamy** [comment]
Hi @Panshark ,
The two error lines in your post indicates that the connection to the CARLA server was broken. Likely because the server stopped or is not running?
Please make sure the server is running and try again. If you run into issues again, please attach the full log file in your reply.

**Comment by Panshark** [comment]
Hi @praveen-palanisamy ,

Here is the full log:
```
Initializing new Carla server...
Initializing new Carla server...
WARNING: No trained model found for this environment. Training from scratch.
Initializing new Carla server...
Initializing new Carla server...
Initializing new Carla server...
Initializing new Carla server...
Initializing new Carla server...
Initializing new Carla server...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Error connecting: (localhost:58402) failed to connect: [Errno 111] Connection refused, attempt 0
ERROR: tcpserver 17828 : error reading message: End of file 
ERROR: tcpserver 17827 : error writing message: Broken pipe 
ERROR: tcpserver 39506 : error reading message: End of file 
ERROR: tcpserver 24278 : error reading message: End of file 
ERROR: tcpserver 39505 : error writing message: Broken pipe 
ERROR: tcpserver 24277 : error writing message: Broken pipe 
global:Episode#:0        ep_reward:-1149513.8107173594   mean_ep_rew:-1149513.8107173594         best_ep_reward:-1149513.8107173594
ERROR: tcpserver 25508 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 0 : error reading message: Operation canceled 
ERROR: tcpserver 0 : error reading message: Operation canceled 
Error during step, terminating episode early Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 67, in write
    self._socket.sendall(header + message)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 316, in step
    obs = self.step_env(action)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 340, in step_env
    self.client.send_control(
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 145, in send_control
    self._control_client.write(pb_message.SerializeToString())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 69, in write
    self._reraise_exception_as_tcp_error('failed to write data', exception)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
environment.carla_gym.envs.carla.tcp.TCPConnectionError: (localhost:21384) failed to write data: [Errno 32] Broken pipe

Clearing Carla server state
ERROR: tcpserver 21382 : error reading message: End of file Initializing new Carla server...
Error during step, terminating episode early Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 67, in write
    self._socket.sendall(header + message)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 316, in step
    obs = self.step_env(action)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 340, in step_env
    self.client.send_control(
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 145, in send_control
    self._control_client.write(pb_message.SerializeToString())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 69, in write
    self._reraise_exception_as_tcp_error('failed to write data', exception)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
environment.carla_gym.envs.carla.tcp.TCPConnectionError: (localhost:44330) failed to write data: [Errno 32] Broken pipe

Clearing Carla server state
ERROR: tcpserver 44328 : error reading message: End of file 
Initializing new Carla server...
ERROR: tcpserver 24278 : error reading message: End of file 
ERROR: tcpserver 39506 : error reading message: End of file 
ERROR: tcpserver 39505 : error writing message: Broken pipe 
ERROR: tcpserver 17828 : error reading message: End of file 
ERROR: tcpserver 17827 : error writing message: Broken pipe 
Error connecting: (localhost:58402) failed to connect: [Errno 111] Connection refused, attempt 1
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
global:Episode#:1        ep_reward:-416539.880988593     mean_ep_rew:-783026.8458529762  best_ep_reward:-416539.880988593
ERROR: tcpserver 25508 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 53828 : error reading message: End of file 
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 24278 : error reading message: End of file 
ERROR: tcpserver 24277 : error writing message: Broken pipe 
ERROR: tcpserver 39506 : error reading message: End of file 
ERROR: tcpserver 39505 : error writing message: Broken pipe 
Error connecting: (localhost:58402) failed to connect: [Errno 111] Connection refused, attempt 2
ERROR: tcpserver 19605 : error reading message: End of file 
ERROR: tcpserver 19604 : error writing message: Broken pipe 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 0 : error reading message: Operation canceled 
global:Episode#:2        ep_reward:-350793.309871722     mean_ep_rew:-638949.0005258914  best_ep_reward:-350793.309871722
ERROR: tcpserver 25508 : error reading message: End of file 
ERROR: tcpserver 17828 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 53828 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Error during step, terminating episode early Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 67, in write
    self._socket.sendall(header + message)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 316, in step
    obs = self.step_env(action)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 340, in step_env
    self.client.send_control(
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 145, in send_control
    self._control_client.write(pb_message.SerializeToString())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 69, in write
    self._reraise_exception_as_tcp_error('failed to write data', exception)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
environment.carla_gym.envs.carla.tcp.TCPConnectionError: (localhost:48876) failed to write data: [Errno 32] Broken pipe

Clearing Carla server state
ERROR: tcpserver Initializing new Carla server...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Error connecting: (localhost:58402) failed to connect: [Errno 111] Connection refused, attempt 3
ERROR: tcpserver 24278 : error reading message: End of file 
Error during reset: Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 224, in reset
    return self.reset_env()
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 272, in reset_env
    scene = self.client.load_settings(settings)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 75, in load_settings
    return self._request_new_episode(carla_settings)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 158, in _request_new_episode
    self._world_client.write(pb_message.SerializeToString())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 64, in write
    raise TCPConnectionError(self._logprefix + 'not connected')
environment.carla_gym.envs.carla.tcp.TCPConnectionError: (localhost:58402) not connected

Clearing Carla server state
Initializing new Carla server...
global:Episode#:3        ep_reward:-319133.8765342036    mean_ep_rew:-558995.2195279695  best_ep_reward:-319133.8765342036
ERROR: tcpserver 19605 : error reading message: End of file 
ERROR: tcpserver 25508 : error reading message: End of file 
Error connecting: (localhost:42652) failed to connect: [Errno 111] Connection refused, attempt 0
ERROR: tcpserver 25507 : error writing message: Broken pipe 
ERROR: tcpserver 39506 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 17828 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 53828 : error reading message: End of file 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([-1.0, 2.0]), end 65 ([0.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 39506 : error reading message: End of file 
ERROR: tcpserver 39505 : error writing message: Broken pipe 
ERROR: tcpserver 42654 : error reading message: End of file 
ERROR: tcpserver 24278 : error reading message: End of file 
ERROR: tcpserver 42653 : error writing message: Broken pipe 
ERROR: tcpserver 19605 : error reading message: End of file 
global:Episode#:4        ep_reward:-732070.2213848312    mean_ep_rew:-593610.2198993418  best_ep_reward:-319133.8765342036
ERROR: tcpserver 25508 : error reading message: End of file 
ERROR: tcpserver 25507 : error writing message: Broken pipe 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 0 : error reading message: Operation canceled 
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
Start pos 21 ([0.0, 1.0]), end 65 ([1.0, 1.0])
Starting new episode...
ERROR: tcpserver 53828 : error reading message: End of file 
ERROR: tcpserver 53827 : error writing message: Broken pipe 
ERROR: tcpserver 17828 : error reading message: End of file 
Error during step, terminating episode early Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 67, in write
    self._socket.sendall(header + message)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 316, in step
    obs = self.step_env(action)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla_env.py", line 340, in step_env
    self.client.send_control(
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/client.py", line 145, in send_control
    self._control_client.write(pb_message.SerializeToString())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 69, in write
    self._reraise_exception_as_tcp_error('failed to write data', exception)
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch8/environment/carla_gym/envs/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
    raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
environment.carla_gym.envs.carla.tcp.TCPConnectionError: (localhost:45909) failed to write data: [Errno 32] Broken pipe

Clearing Carla server state
ERROR: tcpserver 45907 : error reading message: End of file 
ERROR: tcpserver 17827 : error writing message: Broken pipe 
Initializing new Carla server...
```

**Comment by Panshark** [comment]
Thank you for explaining why this problem could happen. 

Besides, do you know any ways to let me use carla on multiple GPUs? I have four GPUs now, but during training, the process could only work on a single GPU.

**Comment by praveen-palanisamy** [comment]
Hi @Panshark , I missed seeing this message until now. Sorry for the delayed response. 

One way to run CARLA on multiple GPUs for training is using [MACAD-Gym](https://github.com/praveen-palanisamy/macad-gym) which finds the GPU with less utilization and launches CARLA server process on that GPU. You can instantiate multiple environments to utilize all of your GPUs.
Hope that helps.

**Comment by Panshark** [comment]
> Hi @Panshark , I missed seeing this message until now. Sorry for the delayed response.
> 
> One way to run CARLA on multiple GPUs for training is using [MACAD-Gym](https://github.com/praveen-palanisamy/macad-gym) which finds the GPU with less utilization and launches CARLA server process on that GPU. You can instantiate multiple environments to utilize all of your GPUs. Hope that helps.

Hi @praveen-palanisamy ,

Thank you for replying. I tried to use 
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
to let CARLA only use GPU No.1 but failed.

Whenever I use CARLA with MACAD-GYM, it always uses the No.0 GPU. The only thing I can do is put my training program on the other GPUs and retain more resources on the No.0 GPU. Do you know how to fix this CARLA simulator always runs at default GPU issue?

**Comment by praveen-palanisamy** [comment]
The environment variable you set in the script may not be in use by the terminal that launches the CARLA server process.

To isolate the issue, please try to run the CARLA server binary directly using this command from a bash terminal: `CUDA_VISIBLE_DEVICES=1 ./CarlaUE4.sh` and see/share the output of `watch nvidia-smi` to identify the Nvidia GPU utilization.

You can also try to force the GPU device ID used for rendering using the SDL flag: `CUDA_VISIBLE_DEVICE=1 SDL_HINT_CUDA_DEVICE=1 ./CarlaUE4.sh -RenderOffscreen`.

Add `-RenderOffscreen` at the end of the above commands if you want to render offscreen (no display) like this: ` `CUDA_VISIBLE_DEVICE=1 SDL_HINT_CUDA_DEVICE=1 ./CarlaUE4.sh -RenderOffscreen`

If you are using MACAD-Gym, and have multiple GPUs and vglrun setup on your system, you should see: `"Running sim servers in headless/multi-GPU mode"` in your MACAD-Gym log file and the CARLA server process should be launched on a less utilized GPU. 
Please confirm with the logfile.

**Comment by praveen-palanisamy** [comment]
@Panshark : I hope the above answer helped to resolve your issue. Since there hasn't been a follow-up in a long while, I am closing this issue. Please feel free to re-open or [create a new discussion](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/discussions) if you have follow-up questions.
